### ISSUE TITLE
"Failed to get recommendations. Please check your AI service settings and try again." using ollama

### ISSUE THREAD

**Issue by mmol67** [fingerthief/recommendarr#108]
I'm getting this message. AI setup works ok, and shows the models, I select one of them, and it is showed in the recommendation page.

Maybe related to this https://github.com/fingerthief/recommendarr/issues/37 ?

OS: Rocky Linux 9.4 + Incus containers + docker

Ollama is running in a OCI container, and it is accessible from OpenWebUI and Python, same host or remote machine.
Recommendar is running in docker inside a LXC container.
Radarr, Sonarr and Plex setup are responding with success.

I'm using last docker image.

![Image](https://github.com/user-attachments/assets/aa0b7e72-6068-4396-bbd7-972b4965a8d9)

**Comment by mmol67** [comment]
Yes, of course. Ah, I forgot to say i'm using last firefox in linux:

`
TypeError: this is undefined bootstrap-autofill.js:1857:9
Error getting TV show recommendations: TypeError: e.map is not a function
    getRecommendations OpenAIService.js:912
    getRecommendations RequestRecommendations.vue:4333
    100 RequestRecommendations.vue:827
    i runtime-core.esm-bundler.js:199
    s runtime-core.esm-bundler.js:206
    n runtime-dom.esm-bundler.js:730
    Z runtime-dom.esm-bundler.js:680
    Q runtime-dom.esm-bundler.js:698
    ae runtime-dom.esm-bundler.js:775
    R runtime-core.esm-bundler.js:4873
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    I runtime-core.esm-bundler.js:5055
    D runtime-core.esm-bundler.js:5130
    g runtime-core.esm-bundler.js:4675
    u runtime-core.esm-bundler.js:5406
    run reactivity.esm-bundler.js:225
    runIfDirty reactivity.esm-bundler.js:263
    i runtime-core.esm-bundler.js:199
    S runtime-core.esm-bundler.js:408
    promise callback*b runtime-core.esm-bundler.js:322
    m runtime-core.esm-bundler.js:317
    scheduler runtime-core.esm-bundler.js:5448
    trigger reactivity.esm-bundler.js:253
    v reactivity.esm-bundler.js:311
    M reactivity.esm-bundler.js:724
    set reactivity.esm-bundler.js:1007
    set runtime-core.esm-bundler.js:3147
    mounted RequestRecommendations.vue:5349
    ge runtime-core.esm-bundler.js:2815
    i runtime-core.esm-bundler.js:199
    s runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2795
    x runtime-core.esm-bundler.js:385
    Y runtime-core.esm-bundler.js:5993
    mount runtime-core.esm-bundler.js:3941
    mount runtime-dom.esm-bundler.js:1767
    4800 main.js:17
    Webpack 5
app.d5ea9ed6.js:1:207779
Failed to get recommendations: TypeError: e.map is not a function
    getRecommendations OpenAIService.js:912
    getRecommendations RequestRecommendations.vue:4333
    100 RequestRecommendations.vue:827
    i runtime-core.esm-bundler.js:199
    s runtime-core.esm-bundler.js:206
    n runtime-dom.esm-bundler.js:730
    Z runtime-dom.esm-bundler.js:680
    Q runtime-dom.esm-bundler.js:698
    ae runtime-dom.esm-bundler.js:775
    R runtime-core.esm-bundler.js:4873
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    C runtime-core.esm-bundler.js:4933
    R runtime-core.esm-bundler.js:4855
    O runtime-core.esm-bundler.js:4820
    g runtime-core.esm-bundler.js:4688
    I runtime-core.esm-bundler.js:5055
    D runtime-core.esm-bundler.js:5130
    g runtime-core.esm-bundler.js:4675
    u runtime-core.esm-bundler.js:5406
    run reactivity.esm-bundler.js:225
    runIfDirty reactivity.esm-bundler.js:263
    i runtime-core.esm-bundler.js:199
    S runtime-core.esm-bundler.js:408
    promise callback*b runtime-core.esm-bundler.js:322
    m runtime-core.esm-bundler.js:317
    scheduler runtime-core.esm-bundler.js:5448
    trigger reactivity.esm-bundler.js:253
    v reactivity.esm-bundler.js:311
    M reactivity.esm-bundler.js:724
    set reactivity.esm-bundler.js:1007
    set runtime-core.esm-bundler.js:3147
    mounted RequestRecommendations.vue:5349
    ge runtime-core.esm-bundler.js:2815
    i runtime-core.esm-bundler.js:199
    s runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2795
    x runtime-core.esm-bundler.js:385
    Y runtime-core.esm-bundler.js:5993
    mount runtime-core.esm-bundler.js:3941
    mount runtime-dom.esm-bundler.js:1767
    4800 main.js:17
    Webpack 5
app.d5ea9ed6.js:1:316921
TypeError: this is undefined bootstrap-autofill.js:1857:9
`

**Comment by fingerthief** [comment]
Can you open the browser dev tools (F12) and look in the console and see what the error is when you try to request?

I've confirmed Ollama works locally or remote when running it through Docker with a few people now, but naturally there are many different setups people have that might throw a wrench into things.

**Comment by mmol67** [comment]
Hello. Maybe you can see it here? 

![Image](https://github.com/user-attachments/assets/cad2b18d-a6a6-4622-afec-2873f8213937)

**Comment by mmol67** [comment]
ummmm trying it without domain, locally, firefox without extensions (except for bitwarden one), and got same error..

```
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    build:
      context: .
    container_name: recommendarr
    ports:
      - ${PORT:-3000}:${PORT:-3000} # Unified port for both frontend and API
    # This is needed to allow the container to access services on the host machine
    # For example, when connecting to Sonarr, Radarr, Plex etc. running on the host (I think?)
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=false
      - PORT=${PORT:-3000}
      - PUBLIC_URL=http://192.168.5.102:3000
      #- PUBLIC_URL=${PUBLIC_URL:-http://localhost:${PORT:-3000}}
      # Uncomment to force secure cookies even over HTTP (only use if behind HTTPS reverse proxy)
      #- FORCE_SECURE_COOKIES=true
    volumes:
      - /mnt/main/conf/u2/recommendarr:/app/server/data
    restart: unless-stopped
networks: {}
```
If you don't see nothing strange in my compose, I will start again the thing from scratch, and then will tell you if it works.
Thank you
