### ISSUE TITLE
App uses (very) old NodeJS (and other package) versions

### ISSUE THREAD

**Issue by sammcj** [fingerthief/recommendarr#41]
Howdy, I went to try out the app and something caught my eye - Looking at the dockerfile I see the application uses the very old NodeJS 16 - The current stable NodeJS version is 22.

A number of the packages in package.json also is very out of date and behind current stable versions, I'd recommend updating these as well as Node.

A small side note - is there any reason there are two separate apps (and thus containers), one for the frontend and one for the api? Perhaps it could simply be one, with a route/path for the API if required.

**Comment by fingerthief** [comment]
Hello! Thanks for checking out the project!

I'll definitely take a look at updating the packages etc..

As for the docker setup that may just be my inexperience with using it, I'm pretty new to docker setup. If it can indeed be just me one docker image then I would much prefer that. 

I'll look into seeing if I can keep it as one container.

 I've been hammering out a lot of new features but it's a point I'm going to let things settle for a bit and work on improving bugs, setup etc...

**Comment by sammcj** [comment]
Cool I thought that might be the case, please don't take my comment as criticism or your hard work, it's merely a tip to something I noticed.

If I get a chance I'll try to raise a PR for some of it.

**Comment by fingerthief** [comment]
I'll take all the info tips I can get haha, there should be a 1.2.4 build being pushed to docker hub currently that has:

- Newer package version
- A single container/image to run
- Bugfixes for initially setting up an AI Service
- README updated with new docker instructions etc..

Let me know if there are any issues with the latest version, I'm definitely liking the single container over two.

**Comment by fingerthief** [comment]
Had to revert due to user issues when updating to this latest version (1.2.4)...reverted to 1.2.3 and will work. on updating the packages at least and get that added in. I aparently blew something up with my docker changes.

**Comment by fingerthief** [comment]
Can try the latest test version to see if everything is working for you. It is now a single image/container again.

 Pull specific version for testing (1.2.35)
---
`docker pull tannermiddleton/recommendarr:1.2.35`

Run test specific version (1.2.35)
---
`docker run -d --name recommendarr -p 3030:3030 -p 3050:3050 -v ${PWD}/server/data:/app/server/data
  tannermiddleton/recommendarr:1.2.35`

Docker Compose (1.2.35)
---
```
version: '3'
services:
  recommendarr:
    build:
      context: .
      args:
        # Build time arguments - set these for the Vue.js build process
        - VUE_APP_API_URL=${VUE_APP_API_URL:-}
        - BASE_URL=${BASE_URL:-}
    container_name: recommendarr
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables
      - PUBLIC_URL=${PUBLIC_URL:-}
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
```
