### ISSUE TITLE
Feature Request: Allow Environment Variables or Config File for Configuration

### ISSUE THREAD

**Issue by itsgiff** [fingerthief/recommendarr#44]
Requesting the ability to configure Recommendarr using either environment variables or a config.yaml file. This would improve flexibility for containerized deployments (e.g., Docker, Kubernetes) while also supporting traditional configurations.
Proposed Implementation

Allow Recommendarr to read configuration values from:

    Environment Variables (for dynamic, container-friendly deployments).
    A config.yaml file (for traditional and structured configurations).

### Option 1: Environment Variables

Suggested environment variables:

```
RADARR_ENABLED: "true"
RADARR_URL: "$RADARR_URL"
RADARR_API_KEY: "$RADARR_API_KEY"

SONARR_ENABLED: "true"
SONARR_URL: "$SONARR_URL"
SONARR_API_KEY: "$SONARR_API_KEY"

PLEX_ENABLED: "true"
PLEX_URL: "$PLEX_ADDR"
PLEX_TOKEN: "$PLEX_TOKEN"

TAUTULLI_ENABLED: "true"
TAUTULLI_URL: "$TAUTULLI_URL"
TAUTULLI_KEY: "$TAUTULLI_KEY"

```
Docker Compose Example

For Docker Compose, users could define environment variables like this:
```

version: "3.9"
services:
  recommendarr:
    image: fingerthief/recommendarr:latest
    environment:
      - RADARR_ENABLED=true
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_ENABLED=true
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - PLEX_ENABLED=true
      - PLEX_URL=${PLEX_ADDR}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TAUTULLI_ENABLED=true
      - TAUTULLI_URL=${TAUTULLI_URL}
      - TAUTULLI_KEY=${TAUTULLI_KEY}

```

### Option 2: config.yaml File

An alternative approach would be to allow users to specify a config.yaml file inside the container, similar to how Scraparr handles configurations (scraparr/config/config.yaml).
Example config.yaml File

```
radarr:
  enabled: true
  url: "http://radarr.local:7878"
  api_key: "your_radarr_api_key"

sonarr:
  enabled: true
  url: "http://sonarr.local:8989"
  api_key: "your_sonarr_api_key"

plex:
  enabled: true
  url: "http://plex.local:32400"
  token: "your_plex_token"

tautulli:
  enabled: true
  url: "http://tautulli.local:8181"
  api_key: "your_tautulli_api_key"
```
Docker Compose Example with Config File:

```
version: "3.9"
services:
  recommendarr:
    image: fingerthief/recommendarr:latest
    volumes:
      - ./config.yaml:/app/config.yaml
```

### Benefits:
✅ Easier Configuration Management – Users can choose the method that best suits their environment.
✅ Security – API keys and credentials can be managed through environment variables or securely stored in a config.yaml file.
✅ Scalability – Works well in containerized environments with dynamic configurations.
✅ Flexibility – Users who prefer YAML-based configurations can keep all settings in a structured file.

### Additional Considerations:
- The app should prioritize environment variables over config.yaml settings if both are present.
- Provide an example config.yaml file in the repository for users to reference.
- Support hot-reloading of config.yaml when changes are detected (if feasible).

Would this be a feasible enhancement? I'm happy to test the implementation if needed. Thanks for considering this feature!
