### ISSUE TITLE
Specify URLs for ui and api for reverse proxy setups

### ISSUE THREAD

**Issue by vosiander** [fingerthief/recommendarr#51]
There should be env variables to specify the backend api as a complete url string. I'm currently using a domain based reverse proxy and want to use https://recommendarr.example.com for the UI and https://api.example.com for backed api.

It should be possible to specify env variables for the frontend container like BASE_URL=https://recommendar.example.com and API_URL=https://api.example.com

**Comment by fingerthief** [comment]
I manually pushed up a 1.2.34 version to docker for testing, I've been having some issues with docker things but if you could try out this test version and see if it works at all that would be amazing. Thanks!

There are the two new env variables **VUE_APP_API_URL** and **BASE_URL**

 Pull specific version for testing (1.2.34)
---
`docker pull tannermiddleton/recommendarr:1.2.34`

Run test specific version (1.2.34)
---
`docker run -d --name recommendarr -p 3030:3030 -p 3050:3050 -e VUE_APP_API_URL=https://api.example.com -e
  BASE_URL=https://recommendarr.example.com -v $(pwd)/server/data:/app/server/data tannermiddleton/recommendarr:latest`

**Comment by v1rusnl** [comment]
Tried the env but get an error 502 in Browser.

```
services:
  recommendarr:
    image: tannermiddleton/recommendarr:1.2.34
    container_name: recommendarr
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - VUE_APP_API_URL=https://recommendarrapi.domain.com
      - BASE_URL=https://recommendarr.domain.com
    volumes:
      - ./recommendarr/data:/app/server/data
    restart: unless-stopped
```

Using Caddy as reverse proxy

```
(tls) {
encode zstd gzip
tls /etc/caddy/fullchain.pem /etc/caddy/privkey.pem {
    protocols tls1.3
}
}

(header) {
header {
                        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload;"
                        X-Xss-Protection "1; mode=block"
                        X-Content-Type-Options "nosniff"
                        X-Frame-Options "SAMEORIGIN"
                        Content-Security-Policy "upgrade-insecure-requests"
                        Content-Security-Policy "frame-ancestors 'self' https://*.v1rus.nl;"
                        Referrer-Policy "same-origin"
                        Cache-Control "public, max-age=15, must-revalidate"
                        Feature-Policy "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vr 'none'"
                        Permissions-Policy "accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), speaker=(), sync-xhr=(), usb=(), vr=()"
                        -Server
       }
}

recommendarr.domain.com {
  import log recommendarr.domain.com
  import tls *
  import header *
  reverse_proxy recommendarr:3030
}

recommendarrapi.domain.com {
  import log recommendarrapi.domain.com
  import tls *
  import header *
  reverse_proxy recommendarr:3050
}
```

**Comment by fingerthief** [comment]
I tracked down an issue with the help of a user. An included file that was specific to my setup was being pushed...Causing havoc in the api.

I've fixed the issue in 1.2.35, I hope.

 Pull specific version for testing (1.2.35)
---
`docker pull tannermiddleton/recommendarr:1.2.35`

Run test specific version (1.2.35)
---
`docker run -d --name recommendarr -p 3030:3030 -p 3050:3050 -v ${PWD}/server/data:/app/server/data
  tannermiddleton/recommendarr:1.2.35`

Docker Compose (1.2.35)
---
```
version: '3'
services:
  recommendarr:
    build:
      context: .
      args:
        # Build time arguments - set these for the Vue.js build process
        - VUE_APP_API_URL=${VUE_APP_API_URL:-}
        - BASE_URL=${BASE_URL:-}
    container_name: recommendarr
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables
      - PUBLIC_URL=${PUBLIC_URL:-}
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
```
