### ISSUE TITLE
Cannot connect to Radarr and Sonarr

### ISSUE THREAD

**Issue by v1rusnl** [fingerthief/recommendarr#52]
Since upgrading to recommendarr:latest and recommendarr-api:latest one hour ago, I am not able to connect to my Radarr and Sonarr intances.

![Image](https://github.com/user-attachments/assets/9ec80b2e-bfa4-4926-8ac1-90942e0665a8)

I tried `http://192.168.2.51:7878` and `https://radarr.my.domain.com` via my Reverse Proxy with no success. Before the upgrade (when all was stored in Browser), I could connect. Both adresses are reachable via Browser. The API keys are definitely correct since I use them successfully with the rest of my Arr Stack.
Logs don't indicate anything wrong.

```
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    depends_on:
      - api
    networks:
      recommendarr_default:
    ports:
      - "3030:80"
    restart: unless-stopped

  api:
    image: tannermiddleton/recommendarr-api:latest
    container_name: recommendarr-api
    networks:
      recommendarr_default:
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      - recommendarr_data:/app/server/data
    restart: unless-stopped
    
networks:
    recommendarr_default:
        external: true
        name: recommendarr_default

volumes:
    recommendarr_data:
```

**Comment by fingerthief** [comment]
Please attempt to use the test build, there have been some docker issues I'm attempting to fix..If you could try a clean install by removing the old version and running the test version below:


 Pull specific version for testing (1.2.34)
---
`docker pull tannermiddleton/recommendarr:1.2.34`

Run test specific version (1.2.34)
---
`docker run -d --name recommendarr -p 3030:3030 -p 3050:3050 -v ${PWD}/server/data:/app/server/data
  tannermiddleton/recommendarr:1.2.34`

**Comment by v1rusnl** [comment]
Yeah just realized you're on 1.2.4 Pre-Release, so I set up tannermiddleton/recommendarr:v1.2.4 and now it's working. Thanks for the fast response. Do I need the seperate API container still in 1.2.4?

**Comment by fingerthief** [comment]
So 1.2.4 was a bugged build people were having issues, so I tried some changes and pushed a test build to **1.2.34** ( I know the versioning is weird) that doesn't require a separate API container.

Technically 1.2.34 should be the latest (commands listed above) and doesn't require the separate container. If you could confirm 1.2.34 works that would be extremely awesome.

**Comment by fingerthief** [comment]
Sorry about that, pushed up a linux/amd64 build to 1.2.34

**Comment by v1rusnl** [comment]
OK my new Compose file:

```
services:
  recommendarr:
    image: tannermiddleton/recommendarr:1.2.34
    container_name: recommendarr
    networks:
      recommendarr_default:
    environment:
      - VUE_APP_API_URL=https://recommendarrapi.domain.com
      - BASE_URL=https://recommendarr.domain.com
    ports:
      - "3030:80"
      - "3050:3050"
    restart: unless-stopped

networks:
    recommendarr_default:
        external: true
        name: recommendarr_default

volumes:
    recommendarr_data:
```

My Docker bridged network the container is on is `172.34.0.0/16`

Error log:
```
API Server starting up in development mode
API server running on port 3050
Loaded existing encryption key
Created data directory: /app/server/data
Loaded and decrypted existing credentials
 INFO  Accepting connections at http://localhost:3030
Proxy request to: http://192.168.0.7:32771/api/v3/system/status (GET)
Proxy request to: http://192.168.0.7:8989/api/v3/system/status (GET)
Proxy request to: http://192.168.0.7:3025/api/v2 (GET)
Proxy error: connect ECONNREFUSED 192.168.0.7:32771
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:32771/api/v3/system/status. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:32771/api/v3/system/status
Proxy error: connect ECONNREFUSED 192.168.0.7:8989
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:8989/api/v3/system/status. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:8989/api/v3/system/status
Proxy error: connect ECONNREFUSED 192.168.0.7:3025
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:3025/api/v2. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:3025/api/v2
Proxy request to: http://192.168.0.7:8989/api/v3/system/status (GET)
Proxy request to: http://192.168.0.7:3025/api/v2 (GET)
Proxy request to: http://192.168.0.7:32771/api/v3/system/status (GET)
Proxy error: connect ECONNREFUSED 192.168.0.7:3025
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:3025/api/v2. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:3025/api/v2
Proxy error: connect ECONNREFUSED 192.168.0.7:32771
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:32771/api/v3/system/status. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:32771/api/v3/system/status
Proxy error: connect ECONNREFUSED 192.168.0.7:8989
Connection error (ECONNREFUSED): Could not connect to the service. Could not connect to http://192.168.0.7:8989/api/v3/system/status. Please verify:
         1. The service is running on that IP
         2. The port is correct and open
         3. Any firewalls allow the connection
         4. The server has network access to that IP Attempted URL: http://192.168.0.7:8989/api/v3/system/status
```

I don't know where the  192.168.0.7 comes from, but I cannot reach the WebUI not at all now.

**Comment by v1rusnl** [comment]
Nevermind. got it working. Did not recognize that you changed port from 80 to 3030.

**Comment by fingerthief** [comment]
I see the issue I believe and likely explains a lot of the recent woes, running some tests and should have build pushed up soon to 1.2.35. An included file that was specific to my setup was being pushed...Causing havoc in the api.

I've fixed the issue in 1.2.35 (will replace 1.2.4), if you could try out this version one last time I'll leave you alone lmao.

 Pull specific version for testing (1.2.35)
---
`docker pull tannermiddleton/recommendarr:1.2.35`

Run test specific version (1.2.345
---
`docker run -d --name recommendarr -p 3030:3030 -p 3050:3050 -v ${PWD}/server/data:/app/server/data
  tannermiddleton/recommendarr:1.2.35`

**Comment by v1rusnl** [comment]
Will test tomorrow morning. 11:50PM here. Thnanks for your work!

**Comment by fingerthief** [comment]
Thanks for your help!

**Comment by v1rusnl** [comment]
The above was tested on Docker Desktop. Switched to another machine (Debian) with also no

**Comment by v1rusnl** [comment]
Is the recommendation history somehow stored inside the container or browser based?

I ask because the connected service (Radarr, Sonarr, OpenAI , Ollama ...) are now persistent across all devices, but the recommendation history is not. I created some recommendations on my PC (
134 total items), and when I open recommendarr on my phone, the history is zero.

**Comment by fingerthief** [comment]
Thanks for all your help in testing this stuff, I'm not a docker expert at all and less of a networking expert so this is all at the edge of knowledge.

Do you have an example of a docker compose that does work? If not that's okay I'll continue tinkering with that bit

You're right the recommendations are stored in the browser still unfortunately but I will update them to be persistent as well soon. I just wanted the app/docker to be functional for others before continuing.

**Comment by v1rusnl** [comment]
Working:
```
services:
  recommendarr:
    build:
      context: .
      args:
        - VUE_APP_API_URL=https://api.example.com
        - BASE_URL=https://recommendarr.example.com
    container_name: recommendarr
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PUBLIC_URL=https://recommendarr.example.com
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped  
```
One question though, is PUBLIC_URL needed as env when args VUE_APP_API_URL and BASE_URL are also set during building process?

*******************************************************************************************

Regarding your example in readme, I'm also no expert at all, but I think it's not possible to modify an existing docker image (yours) with the build option in compose. That would explain why it did not work, since compose output from the readme example gave me no indication of any modifying in contrast when I build from scratch with your source code. I guess the build args VUE_APP_API_URL and BASE_URL are not injected into the prepackaged image, therefor connecting over https does not work.

```
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
.
.
.
    build:
      context: .
      args:
        # Build time URL configuration (optional) 
        - BASE_URL=https://recommendarr.example.com
        - VUE_APP_API_URL=https://api.example.com
```

What I know is that you can delete version: '3' from compose since it's deprecated.

**Comment by fingerthief** [comment]
Thanks for the info and suggestions, I've pushed out an update that has a few tweaks but most importantly like you suggested has a setup section in the web interface for configuring reverse proxy things. I hope this should make the app setup much easier, if you're willing to test it feel free to give it a go!

I'll be very happy if it works and can move on from docker and setup things haha

**Comment by v1rusnl** [comment]
So this is my test compose:
```
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr2
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      - recommendarr2:/app/server/data
    restart: unless-stopped  

volumes:
    recommendarr2: 
```

In both cases (http/https) on first setup, the App Configuration for Public and API URL pops up empty after a few seconds, even when I filled out the form before.

**First run connecting over http with IP:PORT:**
1. Can connect to Radarr and Sonarr instance via http, it does not work on initial setup screen, but when I skip Reverse proxy setup, I get into menu and there the connection check is working for both
2. Cannot connect to OpenAI API -> "Cannot connect to the API server. Please check your connection."
```
Proxy request to: https://api.openai.com/v1/models (GET)
Docker environment detected, processing URL: https://api.openai.com/v1/models
External API call detected, using original URL: https://api.openai.com/v1/models
Proxy response from: https://api.openai.com/v1/models, status: 400
```

**Connecting over https with domain name:**
1. Cannot connect to Radarr and Sonarr instance  -> "Connection failed. Please check your URL and API key."
Therefor I do not get to the menu to test further things. The setup screen is shown on every site entering, even I set up  Radarr and Sonarr over http before.

**Comment by fingerthief** [comment]
Yeah that's the hard part with this stuff hah, I took your test compose put it in my docker-compose file and cleaned all of my previous docker images etc..and ran `docker-compose -d` and it pulled the latest image and lets me connect to everything as expected.

I made sure to delete every docker volume, image and container on the machine before running the compose. It all seems to work for me except I don't have reverse proxy setup to actually test that part.

**Comment by v1rusnl** [comment]
Perhaps it's Docker Desktop specific. Let's see what others say.

**Comment by fingerthief** [comment]
I'm working on testin reverse proxy setup on my side, I think I'm running into the same issue as you so I've got something to work with now.

If I attempt to use a reverse proxy and enter setup info it never saves and just reloads empty...can't connect to anything really.

If I'm not using a reverse proxy to access it and just access it locally it all works fine.

So it seems to be limited to the reverse proxy implmentaion or setup.

**Comment by fingerthief** [comment]
I figured out the issue...So the reverse proxy setup does work properly if you build and pass the args correctly. However the app config page I made will never work how I designed it (my noobness). The args are set at build and can't be updated from the app really.

One thing to note is my docker-compose file was missing passing in the args so that is why attempting to build with that wouldn't work. I've confirmed reverse proxy setup (for myself at least) 

For now the proper reverse proxy setup is to either:

- run a build command and pass in the args  (replace with your URLs)
  - `docker build --build-arg VUE_APP_API_URL=https://api.myapp.recommendarr.com --build-arg PUBLIC_URL=https://myapp.recommendarr.com -t recommendarr:latest .`
  - `docker run -p 3030:3030 -p 3050:3050 -e VUE_APP_API_URL="https://api.myapp.recommendarr.com" -e PUBLIC_URL="https://myapp.recommendarr.com" -v recommendarr-data:/app/server/data . --build`

- use the updated docker-compose and run `docker-compose up -d --build`, obviously replace the URLs with the ones correct for your setup.

```
services:
  recommendarr:
    #IF NOT using a reverse proxy uncomment the image tag to use prebuilt
    #image: tannermiddleton/recommendarr:latest
    # Uncomment and build locally if you need a Reverse Proxy
    build:
      context: .
      args:
        # Build time arguments - set these for the Vue.js build process
        #Reverse proxy example
        - VUE_APP_API_URL=https://api.myapp.recommendarr.com
        #Local example
        #- VUE_APP_API_URL=http://localhost:3050
        - BASE_URL=/
    container_name: recommendarr
    ports:
      - "3030:3030"  # Frontend port
      - "3050:3050"  # Backend API port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables - customize these as needed
      # For local use, the defaults should work without changes
      #- PUBLIC_URL=http://localhost:3030
      #- VUE_APP_API_URL=http://localhost:3050
      # For reverse proxy setups, uncomment and modify these do NOT forget the build section above
      - PUBLIC_URL=https://myapp.recommendarr.com
      - VUE_APP_API_URL=https://api.myapp.recommendarr.com
    volumes:
      - recommendarr-data:/app/server/data
    restart: unless-stopped

volumes:
  recommendarr-data:
```
