### ISSUE TITLE
Login screen loop

### ISSUE THREAD

**Issue by jayscovill** [fingerthief/recommendarr#66]
Running on Docker and I'm sure this is a Layer 8/ID10T error but after the container starts and I try to login with the default creds I briefly see the initial configuration screen but then get kicked back to the login screen/rinse/repeat.  Not seeing anything in the logs for the container that jumps out at me about what's wrong.

Using this docker-compose.yml

```
services:
  recommendarr:
    # IF NOT using a reverse proxy uncomment the image tag to use prebuilt
    image: tannermiddleton/recommendarr:latest
    # For reverse proxy setup uncomment and setup the URLs:
    # build:
    #   context: .
    #   args:
    #    # Build time arguments - set these for the Vue.js build process
    #    #Reverse proxy example
    #    #- VUE_APP_API_URL=https://api.myapp.recommendarr.com
    #    #No Reverse proxy
    #     - VUE_APP_API_URL=${BUILD_API_URL:-http://localhost:3050}
    #     - BASE_URL=${BASE_URL:-/}
    container_name: recommendarr
    ports:
      - "3030:3030"  # Frontend port - must be 3030:3030
      - "3050:3050"  # Backend API port - must be 3050:3050
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables
      # For reverse proxy setups, uncomment and modify these do NOT forget the build section above
      #- PUBLIC_URL=https://myapp.recommendarr.com
      #- VUE_APP_API_URL=https://api.myapp.recommendarr.com
      #- PUBLIC_URL=${PUBLIC_URL:-http://localhost:3030}
      #- VUE_APP_API_URL=${RUNTIME_API_URL:-http://localhost:3050}
    volumes:
      - recommendarr-data:/app/server/data
    restart: unless-stopped

volumes:
  recommendarr-data:
    name: recommendarr-data
    driver: local
```
