### ISSUE TITLE
Make the volume path like any other *arr

### ISSUE THREAD

**Issue by RealBardock** [fingerthief/recommendarr#99]
Make the volume path like any other *arr
path-to-my-files:movies
path-to-my-files:series

**Comment by fingerthief** [comment]
The idea is to connect to your *arr services via the application, not import your media library directly to the application like Sonarr/Radarr. I don't think I'll be making that change anytime soon. Seems a bit unnecessary in my eyes.

**Comment by Anexgohan** [comment]
here you go:

```
  recommendarr:
    # main latest branch:
    image: tannermiddleton/recommendarr:latest
    # dev branch:
    # image: tannermiddleton/recommendarr:dev
    container_name: recommendarr
    environment:
      - TZ=Asia/Kolkata
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3000
      # Runtime environment variables
      # For reverse proxy setups, uncomment and modify these do NOT forget the build section above
      - PUBLIC_URL=http://localhost:3000
      - FORCE_SECURE_COOKIES=false
    volumes:
      - /etc/localtime:/etc/localtime:ro  #read only local time
      - ./docker-data/recommendarr/app/server/data:/app/server/data
    ports:
      - 7654:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
```
